package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class UILoginController {
	@FXML
	private TextField tfID;
	@FXML
	private PasswordField tfPassword;
	@FXML
	private Button bLogin;
	@FXML
	private Button bRegister;

	// Event Listener on Button[#bLogin].onAction
	@FXML
	public void onLogin(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bRegister].onAction
	@FXML
	public void saveRegister(ActionEvent event) {
		// TODO Autogenerated
	}
}
